### ISSUE TITLE
show only a basic html page instead of stlish page

### ISSUE THREAD

**Issue by mjanu145** [anantgarg/Qwench#18]
installed qwench and but there is problem when i open my site it show a basic html page without any design. here is a screenshot.
 now what do i need to config? 
![img1](https://cloud.githubusercontent.com/assets/11726668/6925737/1dd28310-d7ff-11e4-9188-1633f786ba12.png)

**Comment by anantgarg** [comment]
Check if the CSS is loading in Chrome Developer Tools. If not, see what error it is giving.

**Comment by mjanu145** [comment]
solved
