### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by deveshruttala** [anantgarg/Qwench#24]
Fatal error: Uncaught Error: Call to undefined function mysql_connect() in E:\website\webpage\libraries\shared.php:133 Stack trace: #0 E:\website\webpage\libraries\shared.php(206): db() #1 E:\website\webpage\index.php(34): include_once('E:\\website\\webp...') #2 {main} thrown in E:\website\webpage\libraries\shared.php on line 133 

this is the error that i am  facing please help me out @anantgarg

**Comment by FreeBSoD** [comment]
you should switch to a old php version, or change mysql_connect to mysqli_connect
