### ISSUE TITLE
Qwench not working after good installation

### ISSUE THREAD

**Issue by lcardoza** [anantgarg/Qwench#6]
I've installed Qwench and the installation has completed successfully. After access the web site it work fine with one message on first access

"Questions active
Sorry, we could not find what you were looking for. You may want to have a look at tags.
"
and then if I click on any of the menus items like Questions, Tags, Users, Unanswered , Ask or Contribute or register it returns the message

"404 - File or directory not found."

Any suggestions?

**Comment by tgp1994** [comment]
I also want to add - I was running into this issue as well, and I had to remove the .htaccess file **along with** changing the above line. My guess is the server was preconfigured to redirect somehow.
